name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          [cite_start]python-version: '3.11' # [cite: 32]
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Training Script
        [cite_start]run: python scripts/train.py # [cite: 33]
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            model.pkl
            metrics.json 
          # Assuming your script saves these files [cite: 36, 38]

  deploy:
    name: Continuous Deployment
    [cite_start]needs: train # Ensures this only runs if training passed [cite: 41]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          [cite_start]name: model-artifacts # Gets the model trained in the previous job [cite: 42]

      - name: Compare Metrics
        id: compare
        run: |
          # Extracts the metrics value [cite: 37]
          CURRENT_R2=$(jq -r '.r2' metrics.json) 
          BEST_R2=${{ vars.BEST_R2 }}
          
          # Checks if Current Metric > BEST_Metric [cite: 44]
          if (( $(echo "$CURRENT_R2 > $BEST_R2" | bc -l) )); then
            echo "IMPROVED=true" >> $GITHUB_ENV
            echo "CURRENT_R2=$CURRENT_R2" >> $GITHUB_ENV
          else
            [cite_start]echo "2022bcs0068:----Metric did not improve" # [cite: 45]
            echo "IMPROVED=false" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        [cite_start]if: env.IMPROVED == 'true' # Proceeds to build if Yes [cite: 48]
        uses: docker/login-action@v2
        with:
          [cite_start]username: ${{ secrets.DOCKER_USERNAME }} # [cite: 50]
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Image
        if: env.IMPROVED == 'true'
        run: |
          # Builds the image using the Dockerfile [cite: 51]
          docker build -t iiitkabel/wine-model:latest . 
          # Pushes it to DockerHub [cite: 53]
          docker push iiitkabel/wine-model:latest 

      - name: Update Baseline Metric
        if: env.IMPROVED == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Updates the Best Metrics in github variable to the new high score [cite: 56]
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables/BEST_R2 \
            -f name='BEST_R2' -f value="$CURRENT_R2"
